package com.example.javawebtry.mybatis.dao;

import com.example.javawebtry.mybatis.model.Studentgroup;
import java.util.List;

public interface StudentgroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTGROUP
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTGROUP
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    int insert(Studentgroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTGROUP
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    Studentgroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTGROUP
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    List<Studentgroup> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTGROUP
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    int updateByPrimaryKey(Studentgroup record);
}