package com.example.javawebtry.mybatis.dao;

import com.example.javawebtry.mybatis.model.Students;
import java.util.List;

public interface StudentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTS
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTS
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    int insert(Students record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTS
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    Students selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTS
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    List<Students> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTS
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    int updateByPrimaryKey(Students record);
}