package com.example.javawebtry.mybatis.model;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.ID
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.TEACHER
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    private String teacher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.TITLE
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.ID
     *
     * @return the value of PUBLIC.COURSE.ID
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.ID
     *
     * @param id the value for PUBLIC.COURSE.ID
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.TEACHER
     *
     * @return the value of PUBLIC.COURSE.TEACHER
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    public String getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.TEACHER
     *
     * @param teacher the value for PUBLIC.COURSE.TEACHER
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    public void setTeacher(String teacher) {
        this.teacher = teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.TITLE
     *
     * @return the value of PUBLIC.COURSE.TITLE
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.TITLE
     *
     * @param title the value for PUBLIC.COURSE.TITLE
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    public void setTitle(String title) {
        this.title = title;
    }
}