package com.example.javawebtry.mybatis.model;

public class Studentgroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENTGROUP.ID
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENTGROUP.YEAR
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    private Integer year;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENTGROUP.ID
     *
     * @return the value of PUBLIC.STUDENTGROUP.ID
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENTGROUP.ID
     *
     * @param id the value for PUBLIC.STUDENTGROUP.ID
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENTGROUP.YEAR
     *
     * @return the value of PUBLIC.STUDENTGROUP.YEAR
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENTGROUP.YEAR
     *
     * @param year the value for PUBLIC.STUDENTGROUP.YEAR
     *
     * @mbg.generated Mon Feb 26 18:55:46 EET 2024
     */
    public void setYear(Integer year) {
        this.year = year;
    }
}